version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://mongo:27017/chatapp
    depends_on:
      - mongo

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "4200:4200"

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
